### ISSUE TITLE
example/vgg16に必要なdog.pngがないようです

### ISSUE THREAD

**Issue by miyo** [natsutan/cocytus#2]
example/vgg16を試してみようと，kerasの下でvgg16.pyを実行しようとしたのですが，
必要なdog.pngがないようで，エラーになってしまいます．

Using TensorFlow backend.
Traceback (most recent call last):
  File "vgg16.py", line 90, in <module>
    main()
  File "vgg16.py", line 15, in main
    img = image.load_img(img_file, target_size=(224, 224))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/keras/preprocessing/image.py", line 320, in load_img
    img = pil_image.open(path)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PIL/Image.py", line 2410, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '../img/dog.png'

**Comment by natsutan** [comment]
いったんこれで、お願いします。
後でコミットしておきます。

![dog](https://user-images.githubusercontent.com/41741/27780476-1816c082-6004-11e7-8c55-dba979a5e2a9.png)

**Comment by natsutan** [comment]
コミットしました

**Comment by miyo** [comment]
ありがとうございます！
